name: ucfsigai_intro-to-nns
channels:
- conda-forge
dependencies:
- jupyter_core=4.3.0
- jupyter_client=5.1.0
- jupyter_console=5.1.0
- jupyter_latex_envs=1.3.8.2
- jupyter_highlight_selected_word=0.0.10
- jupyter_contrib_nbextensions=0.3.1
- matplotlib=2.0.2
- nbconvert=5.3.1
- numba=0.35.0
- numpy=1.13.1
- pandas=0.20.3
- pip=9.0.1
- plotly=2.0.11
- pytables=3.4.2
- python=3.6.1
- scipy=0.19.1
- scrapy=1.4.0
- seaborn=0.8.0
- tensorflow=1.3.0
- tikzmagic=0.1.0
- pymongo=3.4.0
- pip:
  - colorlover==0.2.1